export type { Apispecialtygetall$Params } from './fn/operations/apispecialtygetall';
export { apispecialtygetall } from './fn/operations/apispecialtygetall';
export type { Apidoctorgetall$Params } from './fn/operations/apidoctorgetall';
export { apidoctorgetall } from './fn/operations/apidoctorgetall';
export type { Apiappointmentinsert$Params } from './fn/operations/apiappointmentinsert';
export { apiappointmentinsert } from './fn/operations/apiappointmentinsert';
export type { Apiappointmentgetall$Params } from './fn/operations/apiappointmentgetall';
export { apiappointmentgetall } from './fn/operations/apiappointmentgetall';
export type { Apiappointmentseen$Params } from './fn/operations/apiappointmentseen';
export { apiappointmentseen } from './fn/operations/apiappointmentseen';
export type { Apiappointmentreject$Params } from './fn/operations/apiappointmentreject';
export { apiappointmentreject } from './fn/operations/apiappointmentreject';
export type { Apiappointmentclose$Params } from './fn/operations/apiappointmentclose';
export { apiappointmentclose } from './fn/operations/apiappointmentclose';
export type { Apiappointmentcomment$Params } from './fn/operations/apiappointmentcomment';
export { apiappointmentcomment } from './fn/operations/apiappointmentcomment';
export type { Apiappointmentcoordination$Params } from './fn/operations/apiappointmentcoordination';
export { apiappointmentcoordination } from './fn/operations/apiappointmentcoordination';
export type { Apiauthlogin$Params } from './fn/operations/apiauthlogin';
export { apiauthlogin } from './fn/operations/apiauthlogin';
export type { Apiauthregister$Params } from './fn/operations/apiauthregister';
export { apiauthregister } from './fn/operations/apiauthregister';
export type { Apidoctorgetbyspecialty$Params } from './fn/operations/apidoctorgetbyspecialty';
export { apidoctorgetbyspecialty } from './fn/operations/apidoctorgetbyspecialty';
export type { Apispecialtyinsert$Params } from './fn/operations/apispecialtyinsert';
export { apispecialtyinsert } from './fn/operations/apispecialtyinsert';
export type { Apispecialtyupdate$Params } from './fn/operations/apispecialtyupdate';
export { apispecialtyupdate } from './fn/operations/apispecialtyupdate';
export type { Apispecialtydelete$Params } from './fn/operations/apispecialtydelete';
export { apispecialtydelete } from './fn/operations/apispecialtydelete';
export type { Apidoctorinsert$Params } from './fn/operations/apidoctorinsert';
export { apidoctorinsert } from './fn/operations/apidoctorinsert';
export type { Apidoctorupdate$Params } from './fn/operations/apidoctorupdate';
export { apidoctorupdate } from './fn/operations/apidoctorupdate';
export type { Apidoctordelete$Params } from './fn/operations/apidoctordelete';
export { apidoctordelete } from './fn/operations/apidoctordelete';